name: Deploy Service (Cloudflare Worker)

on:
  push:
    branches: ['main']
    paths: ['service/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Cloudflare Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "service"
          secrets: |
            PROD_DB_HOST
            PROD_DB_PASSWORD
            PROD_DB_USER
        env:
          PROD_DB_HOST: ${{ secrets.PROD_DB_HOST }}
          PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
          PROD_DB_USER: ${{ secrets.PROD_DB_USER }}
