name: Deploy App (Cloudflare Pages)

on:
  push:
    branches: ['main']
    paths: ['app/**']

env:
  PROJECT_NAME: admin-camilapoeta

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "app"
          command: npm run build && pages deploy --project-name=$PROJECT_NAME